pfnet/pfrl

- .github/auto_assign.yml
- .github/workflows/auto_assign.yml
This PR will enable auto assignment of PR reviewers using GitHub Actions. A reviewer is chosen randomly from the list in `.github/auto_assign.yml` when a PR is opened (excluding the PR's author), which is the config file for https://github.com/kentaro-m/auto-assign-action.
~See https://github.com/pfnet/pfrl/pull/42 for how it works.~ It seems already enabled for this PR. See what `github-actions` bot does.
> Enable auto assignment of PR reviewers

- .github/workflows/auto_assign.yml
See https://github.com/kentaro-m/auto-assign-action/issues/29
Without this change, `auto-assign-action` fails to assign reviewers to PRs from forked repositories. Confirmed on: https://github.com/pfnet/pfrl/pull/54
With this change, it can assign reviewers to such PRs. Confirmed on: https://github.com/pfnet/pfrl/pull/61
> Enable auto review assignment for PRs from forks

- pfrl/agents/trpo.py
- pfrl/functions/bound_by_tanh.py
When I run PFRL code, I get the warning:
```
/Users/prabhat/miniconda3/envs/pfrl/lib/python3.7/site-packages/torch/nn/functional.py:1558: UserWarning: nn.functional.tanh is deprecated. Use torch.tanh instead.
warnings.warn("nn.functional.tanh is deprecated. Use torch.tanh instead.")
```
This is corroborated by https://discuss.pytorch.org/t/torch-tanh-vs-torch-nn-functional-tanh/15897.
> Replace nn.functional.tanh with torch.tanh

- .github/workflows/auto_assign.yml
Activate auto assign only when a PR is opened.
> By default, a workflow only runs when a pull_request_target's activity type is opened, synchronize, or reopened
https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull_request_target
> Activate auto assign only when a PR is opened

- pfrl/agents/categorical_dqn.py
> calculate scalar q_values to log average_q statistics in categorical dqn algorithms

- README.md
Our internal job scheduler was giving an error on `import pfrl` for Python version 3.5.2. 
I just created a new conda environment with Python 3.5.6, and did `pip install -e .` with my master branch (up to date with upstream pfnet/pfrl repo), and ran the following:
```
(pfrl_test) Prabhats-MacBook-Pro:pfrl prabhat$ python
Python 3.5.6 |Anaconda, Inc.| (default, Aug 26 2018, 16:30:03) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pfrl
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/Users/prabhat/pfn/pfrl/pfrl/__init__.py", line 3, in <module>
from pfrl import agents  # NOQA
File "/Users/prabhat/pfn/pfrl/pfrl/agents/__init__.py", line 4, in <module>
from …
```
> Updates the supported Python version in the README

- pfrl/experiments/evaluator.py
`AsyncEvaluator` and `Evaluator` both use common code and functionality for generating a header in the scores.txt file. This PR unifies them.
> Makes common write_header function

- pfrl/agents/dqn.py
- pfrl/agents/state_q_function_actor.py
> Detach greedy_actions before calling cpu()

- pfrl/agent.py
- tests/test_agent.py
This PR fixes save and load of agent to load a model trained with `DataParallel` or `DistributedDataParallel`.
After learning with  `DistributedDataParallel` and loading the model without using  `DistributedDataParallel`, the following error occurred
```
Traceback (most recent call last):
File "./train_dqn_gym.py", line 268, in <module>
main()
File "./train_dqn_gym.py", line 194, in main
agent.load(args.load)
File "/home/shu/workspace/pfrl/packages/pfrl/pfrl/agent.py", line 113, in load
self.__load(dirname, [])
File "/home/shu/workspace/pfrl/packages/pfrl/pfrl/agent.py", line 132, in __load
os.path.join(dirname, "{}.pt".format(attr)), map_location
File "/home/shu/.pyenv/versions/pfrl/lib/python3.7/site-packages/torch/nn/modules/module.py", line 847, in load_state_dict …
```
> Save and load a module trained with DataParallel or DistributedDataParallel 

- pfrl/wrappers/monitor.py
Call _set_mode in Monitor to set the stats type as done [here](https://github.com/openai/gym/blob/67212547ac29296839434324a0d5996e48fae840/gym/wrappers/monitor.py#L103)
> Set stats type

- pfrl/agents/dqn.py
- tests/agents_tests/basetest_training.py
Step_hooks can be registered by users to perform operations like lr decay
after each step.
However, in the current actor-learner implementation, the step_hooks are called
from the actor side, while variables like lr are on the learner side.
Such difference disables the lr decay by step_hooks.
This PR adds hooks to the learner side to re-enable the step_hooks
related to learner.
Since we can specify both steps and n_updates for the learner, we add
two hooks to handle both of them respectively.
1. A `step_hooks` that takes the `effective_timesteps` as args and
performs the same way as the original `step_hooks`.
2. A `optimizer_step_hooks` takes the `optimizer_step` instead of the
`effective_timesteps` as args.
> Add `step_hooks` and `optimizer_step_hooks` to actor-learner

- pfrl/experiments/evaluator.py
- tests/experiments_tests/test_evaluator.py
We currently collect basic performance statistics as well as agent statistics. This PR allows environment statistics to be collected. This gives a lot of flexibility. For example, if you have a binary success task such as grasping, your environment could give a "success" statistic, in addition to the reward. If you have a finance domain, your environment could track "profit" separate from the reward function.
The environment optionally implements two functions: `get_statistics` and `clear_statistics`. If these functions are not implemented, then the evaluator works as it did before (i.e. this PR is backwards compatible). 
- `get_statistics`: Returns the environment statistics. Defaults to returning an empty list if the environment doesn't implement it.
- `clear_statistics`: Clears the …
> Eval stats collector

- examples/atari/reproduction/a3c/train_a3c.py
- examples/atari/train_acer_ale.py
- pfrl/nn/mlp.py
- pfrl/nn/mlp_bn.py
- pfrl/q_functions/dueling_dqn.py
Addresses  #99 and #100
A flake update changed the behavior of ignoring E402 ([ref](https://gitlab.com/pycqa/flake8/-/issues/638)). This PR applies the recommended fix and also handles E741s with a variable rename.
> Fixes flake errors 

- pfrl/experiments/evaluator.py
Currently, environment statistics are not being incorporated into the tensorboard output.
I modified `train_dqn_ale.py` by adding a dummy wrapper:
```
import gym
class ComputeSuccessRate(gym.Wrapper):
def __init__(self, env):
super().__init__(env)
self.success_record = []
def reset(self):
return self.env.reset()
def step(self, action):
obs, r, done, info = self.env.step(action)
return obs, r, done, info
def get_statistics(self):
return [("success_rate", 0.75)]
def clear_statistics(self):
self.success_record = []
```
The wrapper itself is useless, but it returns environment statistics. I've confirmed they appear in tensorboard when I run an experiment with`use_tensorboard`:
> Adds env_stats to record_tb_stats

- setup.py
This PR adds installation of filelock, which is imported but not listed
in the setup.py.
With current master:
```
>>> import pfrl
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/home/tianqi/repository/pfrl/pfrl/__init__.py", line 3, in <module>
from pfrl import agents  # NOQA
File "/home/tianqi/repository/pfrl/pfrl/agents/__init__.py", line 1, in <module>
from pfrl.agents.a2c import A2C  # NOQA
File "/home/tianqi/repository/pfrl/pfrl/agents/a2c.py", line 7, in <module>
from pfrl.utils import clip_l2_grad_norm_
File "/home/tianqi/repository/pfrl/pfrl/utils/__init__.py", line 7, in <module>
from pfrl.utils.pretrained_models import download_model  # NOQA
File "/home/tianqi/repository/pfrl/pfrl/utils/pretrained_models.py", line 14, in <module>
import filelock …
```
> Install filelock

- pfrl/experiments/prepare_output_dir.py
`pfrl.experiments.generate_exp_id()`  generates a experiment ID from serveral sources including `sys.argv`. 
Under certain circumstances, such as distributed or cloud environments, one may want to control generated directory names. 
In this PR, `generate_exp_id()` takes one more parameter `argv`, by which you can feed a custom `argv` as a configuration of experiments and control the output directory name.
> Add parameter to generate_exp_id()

- pfrl/experiments/train_agent_batch.py
This PR adds tensorboard option to `train_agent_batch_with_evaluation`, in addition to #12, though not sure about down side.
> Add use_tensorboard option to batch training

- .pfnci/lint.sh
Resolves #126 
mypy==0.800 searches child directories even if it has no `__init__.py`.
`examples` is kept untouched since it still suffers from "duplicate module" issues.
```
(pfrl) ➜  pfrl git:(mypy-0800) ✗ mypy examples
examples/slimevolley/train_rainbow.py: error: Duplicate module named 'train_rainbow' (also at 'examples/atari/reproduction/rainbow/train_rainbow.py')
examples/slimevolley/train_rainbow.py: error: Are you missing an __init__.py?
Found 2 errors in 1 file (errors prevented further checking)
```
> Switch to mypy>=0.800

- pfrl/experiments/evaluation_hooks.py
- pfrl/experiments/evaluator.py
- pfrl/experiments/train_agent.py
- pfrl/experiments/train_agent_async.py
- pfrl/experiments/train_agent_batch.py
- tests/experiments_tests/test_evaluation_hooks.py
- tests/experiments_tests/test_evaluator.py
- tests/experiments_tests/test_train_agent.py
- tests/experiments_tests/test_train_agent_async.py
- tests/experiments_tests/test_train_agent_batch.py
call evaluation_hooks in `{Async,}Evaluator` instead of `train_agent{,_batch,_async}`.
This PR is a preparation for unifying `evaluation_hooks` to `use_tensorboard` option.
(Interactions with Tensorboard are called in `{Async,}Evaluator`.)
I also added `support_train_agent{,_batch,_async}` attributes to `EvaluationHook` class in order to clarify that which hooks are eligible for each training function (`train_agent_with_evaluation, train_agent_batch_with_evaluation, train_agent_async`).
---
NOTE: This PR breaks backward compatibility of `EvaluationHook.__call__` API. It no longer has `eval_score` argument. Use `eval_stats['mean']` instead (`eval_score` is equivalent to it).
> call evaluation_hooks in Evaluator

- pfrl/utils/batch_states.py
- tests/utils_tests/test_batch_states.py
Recurrent policies expect data collated in a tuple.
> Fix an error related to collation and RNN

- examples/gym/train_dqn_gym.py
- pfrl/experiments/train_agent.py
- tests/experiments_tests/test_train_agent.py
PFRL's `train_agent_with_evaluation` runs evaluation only when training episodes finish. This is good when `env` and `eval_env` are the same environment, e.g., the real-world robot setup or some external program that is hard to run multiple instances of. However, when you can make an `eval_env` instance that is independent from `env`, there is no good reason to wait until training episodes end.
In fact, `train_agent_batch` does not wait until episodes end because when there are multiple training envs waiting until all the episodes end is inefficient and the logic would be complicated.
The downside of waiting until episodes end is that actual evaluation intervals does not follow the value of `eval_interval`. Here is `scores.txt` of `python examples/gym/train_dqn_gym.py --env CartPole-v0 …
> Evaluation during training episodes

- pfrl/utils/pretrained_models.py
To check that this works, simply test the pretrained model commands for the pretrained models. I.e., try using the `--load-pretrained` flag for the pretrained model scripts. It should load the networks and produce good performance. 
Essentially, we just change the URL reference to the pretrained model directory on AWS (done internally within the company). This PR uses that new URL reference so that we can reduce references to chainer.
> Changes reference from chainer to pfrl for pretrained models

- pfrl/agents/ppo.py
The original [method](https://github.com/pfnet/pfrl/blob/67bd517375bf35cd44421e964c518456d4b6f089/pfrl/agents/ppo.py#L158) can cause IndexError in some cases.  
I stumbled on this bug in my experiments and one way to reproduce the error is to modify the method's inputs to `sequences = [sequences[0][:17]]` and `n_items = 4`.
The fix in this PR is simple, it may not be the optimal though.
> fix IndexError due to empty stack

- pfrl/utils/pretrained_models.py
> Remove six dependency in pre-trained models

- pfrl/experiments/train_agent_async.py
This PR adds `use_shared_memory` to share data among agents.
When I try to another method to share data, I got errors.
To solve it,  I would like to add the option in `train_agent_async()`
> add use_shared_memory option

- examples/atari/train_ppo_ale.py
so there's no lazy execution issue when assigning env seeds
> [BUGFIX] use functools.partial instead of lambda

- .pfnci/run.sh
Resolves #158 
Why this PR resolves the issue:
- Since `gym==0.19.0`, `pip install gym` no longer install `pyglet`, which causes this error since the monitor functionality of classic control envs requires pyglet.
- Now users need to install `gym[classic_control]` so that pyglet is also installed.
Both atari_py and opencv-python are included in gym[atari], so it must be safe to stop installing them manually. See https://github.com/openai/gym/blob/a4c3f15e9b0c7525ec9006e92a3bf6bc8bd0a798/setup.py#L11-L19
> Fix CI error due to gym's version

- pfrl/collections/prioritized.py
Resolves #170 .
`float` might be narrower than `Number` as a type, but I don't think this is a issue here since the `_find` function is used with float only.
> Fix mypy error due to numbers.Number

- pfrl/agents/dqn.py
Saving and loading the DQN agent would not save/load four needed attributes:
- self.t
- self.optim_t
- self._cumulative_steps
- self.replay_buffer
This caused the agent to have different a performance when evaluated without killing the program vs when saving the agent, killing the program, resuming the program and loading the agent.
Fig 1 - Training without checkpoints (i.e. same program ran from start to finish)
Fig 2 - Training with checkpoint (i.e., program killed at every t steps and agents loaded from disk)
My proposed solution (working, but applied only to the DQN agent) was to add new save_snapshot and load_snapshot methods on the agent's class (without overwriting the original save and load methods, avoiding saving the replay buffer every time):
```
def save_snapshot(self, …
```
> Fixed save/load problem on dqn.py
